version: '3.8'

services:
  video-learning-manager:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # 持久化数据目录
      - ./data:/app/data
      # 本地视频目录映射（可根据需要修改）
      - ./local-videos:/app/data/local-videos
      # 数据库文件持久化
      - ./video_learning.db:/app/video_learning.db
    environment:
      # 转录模式配置
      - TRANSCRIPTION_MODE=openai
      # OpenAI API配置（建议使用.env文件）
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-7Ptb5d219b821caf56d600b1f70bdf02dec547de3dcJXdVL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.gptsapi.net}
      # 本地Whisper模型配置
      - WHISPER_MODEL=tiny
      - WHISPER_DEVICE=cpu
      - WHISPER_COMPUTE_TYPE=int8
      - WHISPER_NUM_WORKERS=1
      - WHISPER_THREADS=2
      # 并发控制
      - MAX_CONCURRENT_TRANSCRIPTIONS=1
      # 本地视频监控
      - LOCAL_VIDEO_DIR=/app/data/local-videos
      - ENABLE_LOCAL_SCAN=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3